pipeline {
    agent any

    environment {
        IMAGE_NAME = 'imsameur/mini-shop-cicd'
        IMAGE_TAG = "build-${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-docker-cicd') {
                    sh '''
                        docker run --rm \
                          --user "$(id -u):$(id -g)" \
                          -e HOME=/tmp \
                          -v "$PWD/app:/app" \
                          -w /app \
                          node:24-bookworm-slim \
                          sh -c 'npm ci && npm test'
                    '''
                }
            }
        }

        stage('Build Docker image') {
            steps {
                dir('jenkins-docker-cicd') {
                    sh '''
                        docker build \
                          --build-arg APP_VERSION="${IMAGE_TAG}" \
                          -t "${IMAGE_NAME}:${IMAGE_TAG}" \
                          .
                    '''
                }
            }
        }

        stage('Security scan') {
            steps {
                sh '''
                    docker run --rm \
                      -v /var/run/docker.sock:/var/run/docker.sock \
                      -v /tmp/trivy-cache:/root/.cache/ \
                      aquasec/trivy:latest \
                      image \
                      --scanners vuln \
                      --severity HIGH,CRITICAL \
                      --ignore-unfixed \
                      --exit-code 1 \
                      "${IMAGE_NAME}:${IMAGE_TAG}"
                '''
            }
        }

        stage('Push image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKERHUB_USER',
                        passwordVariable: 'DOCKERHUB_TOKEN'
                    )
                ]) {
                    sh '''
                        echo "$DOCKERHUB_TOKEN" | docker login \
                          --username "$DOCKERHUB_USER" \
                          --password-stdin

                        docker push "${IMAGE_NAME}:${IMAGE_TAG}"

                        docker logout
                    '''
                }
            }
        }
    }
}
