pipeline {
    agent any

    environment {
        IMAGE_NAME = 'imsameur/mini-shop-cicd'
        IMAGE_TAG = "build-${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-docker-cicd') {
                    sh '''
                        docker run --rm \
                          --user "$(id -u):$(id -g)" \
                          -e HOME=/tmp \
                          -v "$PWD/app:/app" \
                          -w /app \
                          node:24-bookworm-slim \
                          sh -c 'npm ci && npm test'
                    '''
                }
            }
        }

        stage('Build Docker image') {
            steps {
                dir('jenkins-docker-cicd') {
                    sh '''
                        docker build \
                          --build-arg APP_VERSION="${IMAGE_TAG}" \
                          -t "${IMAGE_NAME}:${IMAGE_TAG}" \
                          .
                    '''
                }
            }
        }
    }
}
