- name: Create application group
  ansible.builtin.group:
    name: "{{ app_group }}"
    system: true
    state: present

- name: Create application user
  ansible.builtin.user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    home: "{{ app_dir }}"
    create_home: false
    shell: /sbin/nologin
    system: true
    state: present
