{
 "title": "Kubernetes & Linux Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  node_filesystem_avail_bytes{mountpoint=\"/data\",fstype=\"xfs\"}\r\n  /\r\n  node_filesystem_size_bytes{mountpoint=\"/data\",fstype=\"xfs\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase == 1)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Kubernetes Pod Readiness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\"} == 1) or vector(0)",
     "legendFormat": "Ready Pods"
    },
    {
     "expr": "sum(kube_pod_status_ready{condition=\"false\"} == 1) or vector(0)",
     "legendFormat": "Not Ready Pods"
    }
   ]
  }
 ]
}