# Example only. Do not apply this file.
apiVersion: v1
kind: Secret
metadata:
  name: mini-shop-secret-example
  namespace: kubernetes-nodejs
type: Opaque
stringData:
  MONGO_INITDB_ROOT_PASSWORD: "REPLACE_WITH_A_RANDOM_ROOT_PASSWORD"
  MONGO_APP_PASSWORD: "REPLACE_WITH_A_RANDOM_APP_PASSWORD"
